<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8e10ce3c-d38a-41be-aeb8-ce2e2ce0a828</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssessmentBL\AssessmentBL.csproj" />
    <ProjectReference Include="..\UsersBL\UsersBL.csproj" />
    <ProjectReference Include="..\ContentBL\ContentBL.csproj" />
    <ProjectReference Include="..\AIIntegration\AIIntegration.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>